version: "3.8"

# Portainer Stack for Atlas - YouTube Research Pipeline
# Deploy via Portainer > Stacks > Add Stack > Upload or paste this file
# Set environment variables in Portainer's "Environment variables" section
#
# Image will be: ghcr.io/<github-username>/atlas:latest
# Replace GITHUB_USER with your GitHub username

services:
  atlas:
    image: ghcr.io/sudipta26889/atlas:${TAG:-latest}
    environment:
      # API Keys (set these in Portainer environment variables)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - YOUTUBE_PROXY=${YOUTUBE_PROXY:-}
      # MySQL Configuration
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-atlas_db}
      # Google OAuth Configuration (optional - app works without auth if not set)
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - APP_URL=${APP_URL:-http://localhost:7860}
      # History Tab Access Control (comma-separated emails, empty = allow all)
      - ALLOWED_HISTORY_EMAILS=${ALLOWED_HISTORY_EMAILS:-}
      # Gradio Configuration
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_ANALYTICS_ENABLED=False
    ports:
      - "${ATLAS_PORT:-7860}:7860"
    volumes:
      - atlas_output:/app/output
    networks:
      - atlas_net
    # For non-Swarm (Docker Compose) mode - ignored in Swarm
    restart: unless-stopped
    # For Swarm mode - shows warnings in non-Swarm but is mostly ignored
    # Note: deploy.resources.limits works in both modes
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      # Resource limits work in both Swarm and non-Swarm modes
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

volumes:
  atlas_output:
    driver: local

networks:
  atlas_net:
    # bridge works in both Swarm and non-Swarm modes
    # For Swarm mode, you can change to 'overlay' if needed
    driver: bridge
    # attachable works in both modes (allows external containers to connect)
    attachable: true
